- name: Server | Search for Ubuntu AMI
  ec2_ami_search:
     region: "{{ vpc_region|default('us-east-1') }}"
     distro: "{{ linux_distribution }}"
     release: "{{ ubuntu_release }}"
     store: "{{ ami_store }}"
     virt: "{{ virutalization_type }}"
     arch: "{{ cpu_architecture }}"
  register: image_id
