- name: VPC | Creating an AWS VPC inside mentioned Region
  local_action:
    module: ec2_vpc
    state: present
    region: "{{ vpc_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
    subnets: "{{ vpc_subnets }}"
    internet_gateway: "yes"
    route_tables: "{{ vpc_route_tables }}"
    wait: true
    resource_tags: { "Name":"{{ vpc_name }}-vpc" }
  register: vpc

- name: VPC | Write vpc id to file inside the vars directory
  shell: echo "{{ vpc.vpc_id }}" > "{{ vpc_name }}-vpc-info.yml"
  args:
    chdir: aws/vars/

- name: VPC | Write public and private subnets id to files inside the vars directory
  shell: echo "{{ item.id }}" > "{{ item.resource_tags.Name }}.yml"
  args:
    chdir: aws/vars/
  with_items: "{{ vpc.subnets }}"

- name: VPC | Set the public and private subnet id as facts
  set_fact:
    vpc_id: "{{ lookup('file', 'aws/vars/' + vpc_name + '-vpc-info.yml') }}"
    vpc_subnet_1: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + vpc_az_1 + '-subnet.yml') }}"
